version: '3.8'

services:
  app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - .:/app
    ports:
      - "8000:8000"

 prometheus:
    image: prom/prometheus:latest
    volumes:
      # Map the whole folder instead of the specific file
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
